"""tabla picking

Revision ID: 172ae8a01590
Revises: bf21c9318db2
Create Date: 2026-03-26 17:21:31.341748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172ae8a01590'
down_revision = 'bf21c9318db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas_picking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Integer(), nullable=False),
    sa.Column('cantidad_recogida', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('operario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('referencia_documento', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.String(length=30), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas_picking')
    # ### end Alembic commands ###
