"""add pedidos_siesa read model

Revision ID: 1b2332f0b0b1
Revises: 7ddf7d34cd5b
Create Date: 2026-03-31 18:28:40.680258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2332f0b0b1'
down_revision = '7ddf7d34cd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_siesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_docto', sa.String(length=10), nullable=False),
    sa.Column('consec_docto', sa.Integer(), nullable=False),
    sa.Column('centro_op', sa.String(length=10), nullable=False),
    sa.Column('bodega', sa.String(length=10), nullable=False),
    sa.Column('numero_pedido', sa.String(length=20), nullable=False),
    sa.Column('item_codigo', sa.String(length=50), nullable=True),
    sa.Column('item_descripcion', sa.String(length=200), nullable=True),
    sa.Column('item_id_siesa', sa.String(length=50), nullable=True),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('fecha_entrega', sa.String(length=20), nullable=True),
    sa.Column('estado_siesa', sa.Integer(), nullable=True),
    sa.Column('cantidad_pedida', sa.Float(), nullable=True),
    sa.Column('cantidad_remisionada', sa.Float(), nullable=True),
    sa.Column('cantidad_pendiente', sa.Float(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_docto', 'consec_docto', 'centro_op', 'bodega', 'item_codigo', name='uq_pedido_siesa_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos_siesa')
    # ### end Alembic commands ###
