"""tablas recepcion

Revision ID: 48d21cb78869
Revises: 8f6805c05ed7
Create Date: 2026-03-26 18:22:43.548816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d21cb78869'
down_revision = '8f6805c05ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recepciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('numero_oc_siesa', sa.String(length=50), nullable=False),
    sa.Column('proveedor_codigo', sa.String(length=50), nullable=True),
    sa.Column('proveedor_nombre', sa.String(length=200), nullable=True),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('recepcionista_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('es_parcial', sa.Boolean(), nullable=True),
    sa.Column('tiene_excesos', sa.Boolean(), nullable=True),
    sa.Column('tiene_cross_dock', sa.Boolean(), nullable=True),
    sa.Column('siesa_triggered', sa.Boolean(), nullable=True),
    sa.Column('siesa_response', sa.Text(), nullable=True),
    sa.Column('siesa_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_confirmacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['recepcionista_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('items_recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_ordenada', sa.Integer(), nullable=False),
    sa.Column('tolerancia_exceso_pct', sa.Float(), nullable=True),
    sa.Column('cantidad_recibida', sa.Integer(), nullable=True),
    sa.Column('destino', sa.String(length=20), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_cross_dock_id', sa.Integer(), nullable=True),
    sa.Column('ingresado_inventario', sa.Boolean(), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['recepciones.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_cross_dock_id'], ['ubicaciones.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_recepcion')
    op.drop_table('recepciones')
    # ### end Alembic commands ###
