"""add siesa_triggered to tareas_devolucion

Revision ID: 5bdcedc43de0
Revises: a8b9c0d1e2f3
Create Date: 2026-04-24 23:17:21.080788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdcedc43de0'
down_revision = 'a8b9c0d1e2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.alter_column('disponible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('ix_conductores_usuario_id'))
        batch_op.drop_constraint(batch_op.f('conductores_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('items_solicitud_traslado', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('items_solicitud_traslado_solicitud_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'solicitudes_traslado', ['solicitud_id'], ['id'])

    with op.batch_alter_table('lpn', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='LPN-0000001 — secuencial opaco, nunca embedar factor aquí',
               existing_nullable=False)
        batch_op.alter_column('empaque_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Template del empaque — NULL si es LPN huérfano (sin GS1)',
               existing_nullable=True)
        batch_op.alter_column('factor_conversion',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Copia del factor al momento de creación — inmutable aunque cambie el empaque',
               existing_nullable=False)
        batch_op.alter_column('cantidad_actual',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unidades base reales en esta paca (puede ser < factor si está parcialmente abierta)',
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='ACTIVO | EN_TRANSITO | CONSUMIDO',
               existing_nullable=False)
        batch_op.alter_column('recepcion_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Recepción que creó este LPN — trazabilidad completa',
               existing_nullable=True)
        batch_op.alter_column('traslado_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Traslado activo que transporta este LPN',
               existing_nullable=True)
        batch_op.alter_column('notas',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Observaciones del operario al crear el LPN',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_lpn_almacen_id'))
        batch_op.drop_index(batch_op.f('ix_lpn_codigo'))
        batch_op.drop_index(batch_op.f('ix_lpn_estado'))
        batch_op.drop_index(batch_op.f('ix_lpn_producto_id'))

    with op.batch_alter_table('producto_empaques', schema=None) as batch_op:
        batch_op.alter_column('referencia_item',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='codigo_siesa del producto — para re-sync sin JOIN',
               existing_nullable=False)
        batch_op.alter_column('codigo_barras',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Lo que lee el scanner: DUN-14, EAN-13 de caja, LPN-XXXXXXX',
               existing_nullable=False)
        batch_op.alter_column('unidad_medida',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='CAJ, PACA, PAQ, DOC, UND — según Siesa',
               existing_nullable=False)
        batch_op.alter_column('factor_conversion',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Cuántas unidades base (UND) contiene este empaque',
               existing_nullable=False)
        batch_op.alter_column('origen',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='SIESA_GS1: vino del worker | WMS_LPN: creado manualmente en recepción',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_producto_empaques_codigo_barras'))
        batch_op.drop_index(batch_op.f('ix_producto_empaques_producto_id'))
        batch_op.drop_index(batch_op.f('ix_producto_empaques_referencia_item'))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_codigo_barras'))

    with op.batch_alter_table('recaudos_entrega', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recaudos_ruta_id'))
        batch_op.drop_index(batch_op.f('ix_recaudos_tarea_id'))

    with op.batch_alter_table('rutas_despacho', schema=None) as batch_op:
        batch_op.alter_column('estado_financiero',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'PENDIENTE'::character varying"))

    with op.batch_alter_table('siesa_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siesa_jobs_estado'))
        batch_op.drop_index(batch_op.f('ix_siesa_jobs_proximo_intento'))
        batch_op.drop_index(batch_op.f('ix_siesa_jobs_referencia'))

    with op.batch_alter_table('siesa_mapeo_unidades', schema=None) as batch_op:
        batch_op.alter_column('tipo_inv_siesa',
               existing_type=sa.VARCHAR(length=50),
               comment='Valor exacto de f120_id_tipo_inv_serv en Siesa',
               existing_nullable=False)
        batch_op.alter_column('unidad_negocio_id',
               existing_type=sa.VARCHAR(length=10),
               comment='Código Siesa: 001=PAPELERIA 011=HOGAR 014=IMPRESION etc.',
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=200),
               comment='Nota libre del administrador',
               existing_nullable=True)

    with op.batch_alter_table('solicitudes_traslado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_traslado_estado'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_traslado_solicitante'))

    with op.batch_alter_table('tareas_devolucion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siesa_triggered', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('tareas_reposicion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tareas_reposicion_abastecedor_id'))
        batch_op.drop_index(batch_op.f('ix_tareas_reposicion_estado'))
        batch_op.drop_index(batch_op.f('ix_tareas_reposicion_producto_id'))

    with op.batch_alter_table('ubicaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ubicaciones_tipo_zona'))

    with op.batch_alter_table('ubicaciones_huerfanas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ubicaciones_huerfanas_bodega_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ubicaciones_huerfanas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ubicaciones_huerfanas_bodega_id'), ['bodega_id'], unique=False)

    with op.batch_alter_table('ubicaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ubicaciones_tipo_zona'), ['tipo_zona'], unique=False)

    with op.batch_alter_table('tareas_reposicion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tareas_reposicion_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_reposicion_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_reposicion_abastecedor_id'), ['abastecedor_id'], unique=False)

    with op.batch_alter_table('tareas_devolucion', schema=None) as batch_op:
        batch_op.drop_column('siesa_triggered')

    with op.batch_alter_table('solicitudes_traslado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_traslado_solicitante'), ['solicitante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_traslado_estado'), ['estado'], unique=False)

    with op.batch_alter_table('siesa_mapeo_unidades', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nota libre del administrador',
               existing_nullable=True)
        batch_op.alter_column('unidad_negocio_id',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Código Siesa: 001=PAPELERIA 011=HOGAR 014=IMPRESION etc.',
               existing_nullable=False)
        batch_op.alter_column('tipo_inv_siesa',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Valor exacto de f120_id_tipo_inv_serv en Siesa',
               existing_nullable=False)

    with op.batch_alter_table('siesa_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siesa_jobs_referencia'), ['referencia_tipo', 'referencia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_siesa_jobs_proximo_intento'), ['proximo_intento'], unique=False)
        batch_op.create_index(batch_op.f('ix_siesa_jobs_estado'), ['estado'], unique=False)

    with op.batch_alter_table('rutas_despacho', schema=None) as batch_op:
        batch_op.alter_column('estado_financiero',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDIENTE'::character varying"))

    with op.batch_alter_table('recaudos_entrega', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recaudos_tarea_id'), ['tarea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recaudos_ruta_id'), ['ruta_id'], unique=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_codigo_barras'), ['codigo_barras'], unique=False)

    with op.batch_alter_table('producto_empaques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_producto_empaques_referencia_item'), ['referencia_item'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_empaques_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_producto_empaques_codigo_barras'), ['codigo_barras'], unique=False)
        batch_op.alter_column('origen',
               existing_type=sa.VARCHAR(length=20),
               comment='SIESA_GS1: vino del worker | WMS_LPN: creado manualmente en recepción',
               existing_nullable=False)
        batch_op.alter_column('factor_conversion',
               existing_type=sa.INTEGER(),
               comment='Cuántas unidades base (UND) contiene este empaque',
               existing_nullable=False)
        batch_op.alter_column('unidad_medida',
               existing_type=sa.VARCHAR(length=20),
               comment='CAJ, PACA, PAQ, DOC, UND — según Siesa',
               existing_nullable=False)
        batch_op.alter_column('codigo_barras',
               existing_type=sa.VARCHAR(length=50),
               comment='Lo que lee el scanner: DUN-14, EAN-13 de caja, LPN-XXXXXXX',
               existing_nullable=False)
        batch_op.alter_column('referencia_item',
               existing_type=sa.VARCHAR(length=50),
               comment='codigo_siesa del producto — para re-sync sin JOIN',
               existing_nullable=False)

    with op.batch_alter_table('lpn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lpn_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lpn_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_lpn_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_lpn_almacen_id'), ['almacen_id'], unique=False)
        batch_op.alter_column('notas',
               existing_type=sa.TEXT(),
               comment='Observaciones del operario al crear el LPN',
               existing_nullable=True)
        batch_op.alter_column('traslado_id',
               existing_type=sa.INTEGER(),
               comment='Traslado activo que transporta este LPN',
               existing_nullable=True)
        batch_op.alter_column('recepcion_id',
               existing_type=sa.INTEGER(),
               comment='Recepción que creó este LPN — trazabilidad completa',
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               comment='ACTIVO | EN_TRANSITO | CONSUMIDO',
               existing_nullable=False)
        batch_op.alter_column('cantidad_actual',
               existing_type=sa.INTEGER(),
               comment='Unidades base reales en esta paca (puede ser < factor si está parcialmente abierta)',
               existing_nullable=False)
        batch_op.alter_column('factor_conversion',
               existing_type=sa.INTEGER(),
               comment='Copia del factor al momento de creación — inmutable aunque cambie el empaque',
               existing_nullable=False)
        batch_op.alter_column('empaque_id',
               existing_type=sa.INTEGER(),
               comment='Template del empaque — NULL si es LPN huérfano (sin GS1)',
               existing_nullable=True)
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=20),
               comment='LPN-0000001 — secuencial opaco, nunca embedar factor aquí',
               existing_nullable=False)

    with op.batch_alter_table('items_solicitud_traslado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('items_solicitud_traslado_solicitud_id_fkey'), 'solicitudes_traslado', ['solicitud_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conductores_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_conductores_usuario_id'), ['usuario_id'], unique=True)
        batch_op.alter_column('disponible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    # ### end Alembic commands ###
