"""add rm_tipo rm_consec to TareaPacking

Revision ID: 7d08d3a13326
Revises: j4k5l6m7n8o9
Create Date: 2026-05-06 16:44:58.765115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d08d3a13326'
down_revision = 'j4k5l6m7n8o9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bultos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bultos_ruta_estado'))
        batch_op.drop_index(batch_op.f('ix_bultos_tarea_id'))

    with op.batch_alter_table('lpn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lpn_traslado_estado'))

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_movimientos_almacen_fecha'))

    with op.batch_alter_table('pedidos_siesa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_siesa_numero_pedido'))

    with op.batch_alter_table('recaudos_entrega', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recaudos_entrega_ruta_id'))
        batch_op.drop_index(batch_op.f('ix_recaudos_entrega_tarea_id'))

    with op.batch_alter_table('recepciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recepciones_oc_estado'))

    with op.batch_alter_table('rutas_despacho', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rutas_despacho_conductor_estado'))
        batch_op.drop_index(batch_op.f('ix_rutas_despacho_conductor_id'))
        batch_op.drop_index(batch_op.f('ix_rutas_despacho_estado'))
        batch_op.drop_index(batch_op.f('ix_rutas_despacho_fecha_creacion'))
        batch_op.drop_index(batch_op.f('ix_rutas_despacho_vehiculo_id'))

    with op.batch_alter_table('sesiones_conteo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_conteo_almacen_estado'))
        batch_op.drop_index(batch_op.f('ix_sesiones_conteo_estado'))
        batch_op.drop_index(batch_op.f('ix_sesiones_conteo_operario_id'))
        batch_op.drop_index(batch_op.f('ix_sesiones_conteo_producto_ubicacion_estado'))

    with op.batch_alter_table('siesa_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siesa_jobs_tipo_ref_estado'))

    with op.batch_alter_table('tareas_packing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rm_tipo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('rm_consec', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_tareas_packing_empacador_id'))
        batch_op.drop_index(batch_op.f('ix_tareas_packing_estado'))
        batch_op.drop_index(batch_op.f('ix_tareas_packing_estado_siesa_triggered'))
        batch_op.drop_index(batch_op.f('ix_tareas_packing_numero_pedido_siesa'))
        batch_op.drop_index(batch_op.f('ix_tareas_packing_siesa_triggered'))

    with op.batch_alter_table('tareas_picking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tareas_picking_almacen_estado'))
        batch_op.drop_index(batch_op.f('ix_tareas_picking_estado'))
        batch_op.drop_index(batch_op.f('ix_tareas_picking_operario_id'))
        batch_op.drop_index(batch_op.f('ix_tareas_picking_referencia_documento'))

    with op.batch_alter_table('tareas_reposicion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tareas_reposicion_almacen_estado'))
        batch_op.drop_index(batch_op.f('ix_tareas_reposicion_estado'))

    with op.batch_alter_table('ubicaciones_productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ubicaciones_productos_producto_id'))
        batch_op.drop_index(batch_op.f('ix_ubicaciones_productos_ubicacion_producto'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ubicaciones_productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ubicaciones_productos_ubicacion_producto'), ['ubicacion_id', 'producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ubicaciones_productos_producto_id'), ['producto_id'], unique=False)

    with op.batch_alter_table('tareas_reposicion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tareas_reposicion_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_reposicion_almacen_estado'), ['almacen_id', 'estado'], unique=False)

    with op.batch_alter_table('tareas_picking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tareas_picking_referencia_documento'), ['referencia_documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_picking_operario_id'), ['operario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_picking_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_picking_almacen_estado'), ['almacen_id', 'estado'], unique=False)

    with op.batch_alter_table('tareas_packing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tareas_packing_siesa_triggered'), ['siesa_triggered'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_packing_numero_pedido_siesa'), ['numero_pedido_siesa'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_packing_estado_siesa_triggered'), ['estado', 'siesa_triggered'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_packing_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_tareas_packing_empacador_id'), ['empacador_id'], unique=False)
        batch_op.drop_column('rm_consec')
        batch_op.drop_column('rm_tipo')

    with op.batch_alter_table('siesa_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siesa_jobs_tipo_ref_estado'), ['tipo', 'referencia_tipo', 'referencia_id', 'estado'], unique=False)

    with op.batch_alter_table('sesiones_conteo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_conteo_producto_ubicacion_estado'), ['producto_id', 'ubicacion_id', 'estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_sesiones_conteo_operario_id'), ['operario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sesiones_conteo_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_sesiones_conteo_almacen_estado'), ['almacen_id', 'estado'], unique=False)

    with op.batch_alter_table('rutas_despacho', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rutas_despacho_vehiculo_id'), ['vehiculo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rutas_despacho_fecha_creacion'), [sa.literal_column('fecha_creacion DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_rutas_despacho_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_rutas_despacho_conductor_id'), ['conductor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rutas_despacho_conductor_estado'), ['conductor_id', 'estado'], unique=False)

    with op.batch_alter_table('recepciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recepciones_oc_estado'), ['numero_oc_siesa', 'estado'], unique=False)

    with op.batch_alter_table('recaudos_entrega', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recaudos_entrega_tarea_id'), ['tarea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recaudos_entrega_ruta_id'), ['ruta_id'], unique=False)

    with op.batch_alter_table('pedidos_siesa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_siesa_numero_pedido'), ['numero_pedido'], unique=False)

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_movimientos_almacen_fecha'), ['almacen_id', sa.literal_column('fecha DESC')], unique=False)

    with op.batch_alter_table('lpn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lpn_traslado_estado'), ['traslado_id', 'estado'], unique=False)

    with op.batch_alter_table('bultos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bultos_tarea_id'), ['tarea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bultos_ruta_estado'), ['ruta_despacho_id', 'estado'], unique=False)

    # ### end Alembic commands ###
