"""tabla tareas_devolucion logistica inversa

Revision ID: 7ddf7d34cd5b
Revises: 3f9a1c7d2e85
Create Date: 2026-03-30 19:07:08.806154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddf7d34cd5b'
down_revision = '3f9a1c7d2e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas_devolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_diferencia', sa.Integer(), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('es_averiado', sa.Boolean(), nullable=True),
    sa.Column('recepcionista_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('origen_reconciliacion', sa.String(length=50), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['recepcionista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas_devolucion')
    # ### end Alembic commands ###
