"""tablas packing

Revision ID: 8f6805c05ed7
Revises: 172ae8a01590
Create Date: 2026-03-26 17:51:31.769622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6805c05ed7'
down_revision = '172ae8a01590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas_packing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('numero_pedido_siesa', sa.String(length=50), nullable=False),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('empacador_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('verificacion_exitosa', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('siesa_triggered', sa.Boolean(), nullable=True),
    sa.Column('siesa_response', sa.Text(), nullable=True),
    sa.Column('siesa_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_verificado', sa.DateTime(), nullable=True),
    sa.Column('fecha_despachado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['empacador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('items_packing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_esperada', sa.Integer(), nullable=False),
    sa.Column('cantidad_real', sa.Integer(), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('observacion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas_packing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_packing')
    op.drop_table('tareas_packing')
    # ### end Alembic commands ###
