"""add cliente fecha_cargado to tareas_packing

Revision ID: ae625995b0bf
Revises: bd27bd10f4ec
Create Date: 2026-03-31 23:28:06.258786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae625995b0bf'
down_revision = 'bd27bd10f4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas_packing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('fecha_cargado', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas_packing', schema=None) as batch_op:
        batch_op.drop_column('fecha_cargado')
        batch_op.drop_column('cliente')

    # ### end Alembic commands ###
