"""add municipio to pedidos_siesa and tareas_packing

Revision ID: bac7ab565ce1
Revises: ae625995b0bf
Create Date: 2026-04-01 08:09:24.919803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac7ab565ce1'
down_revision = 'ae625995b0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_siesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipio', sa.String(length=100), nullable=True))

    with op.batch_alter_table('tareas_packing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipio', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas_packing', schema=None) as batch_op:
        batch_op.drop_column('municipio')

    with op.batch_alter_table('pedidos_siesa', schema=None) as batch_op:
        batch_op.drop_column('municipio')

    # ### end Alembic commands ###
