"""add puede_picar puede_empacar to usuarios

Revision ID: bd27bd10f4ec
Revises: 1b2332f0b0b1
Create Date: 2026-03-31 22:24:36.365797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd27bd10f4ec'
down_revision = '1b2332f0b0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puede_picar', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('puede_empacar', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('puede_empacar')
        batch_op.drop_column('puede_picar')

    # ### end Alembic commands ###
