"""tablas iniciales wms

Revision ID: bf21c9318db2
Revises: 
Create Date: 2026-03-26 15:16:48.666646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf21c9318db2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('volumen', sa.Float(), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('stock_maximo', sa.Integer(), nullable=True),
    sa.Column('punto_pedido', sa.Integer(), nullable=True),
    sa.Column('clasificacion_abc', sa.String(length=1), nullable=True),
    sa.Column('codigo_siesa', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('zona', sa.String(length=50), nullable=True),
    sa.Column('pasillo', sa.String(length=10), nullable=True),
    sa.Column('estante', sa.String(length=10), nullable=True),
    sa.Column('nivel', sa.String(length=10), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('almacen_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('saldo_antes', sa.Integer(), nullable=True),
    sa.Column('saldo_despues', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('siesa_sync', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('ubicaciones_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('reservado', sa.Integer(), nullable=True),
    sa.Column('bloqueado', sa.Integer(), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.CheckConstraint('cantidad >= 0', name='ck_cantidad_no_negativa'),
    sa.CheckConstraint('reservado >= 0', name='ck_reservado_no_negativo'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ubicacion_id', 'producto_id', 'lote', name='uq_ubicacion_producto_lote')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicaciones_productos')
    op.drop_table('movimientos_inventario')
    op.drop_table('usuarios')
    op.drop_table('ubicaciones')
    op.drop_table('productos')
    op.drop_table('almacenes')
    # ### end Alembic commands ###
