"""tablas conteo ciclico abc

Revision ID: e2808116ca1a
Revises: 48d21cb78869
Create Date: 2026-03-26 18:45:43.606208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2808116ca1a'
down_revision = '48d21cb78869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones_conteo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('clasificacion_abc', sa.String(length=1), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('almacen_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('producto_codigo_siesa', sa.String(length=50), nullable=True),
    sa.Column('maneja_lote', sa.Boolean(), nullable=True),
    sa.Column('operario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('existencia_siesa', sa.Integer(), nullable=True),
    sa.Column('cantidad_fisica', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.String(length=50), nullable=True),
    sa.Column('diferencia', sa.Integer(), nullable=True),
    sa.Column('motivo_codigo', sa.String(length=20), nullable=True),
    sa.Column('es_segundo_conteo', sa.Boolean(), nullable=True),
    sa.Column('sesion_origen_id', sa.Integer(), nullable=True),
    sa.Column('segundo_operario_id', sa.Integer(), nullable=True),
    sa.Column('siesa_triggered', sa.Boolean(), nullable=True),
    sa.Column('siesa_response', sa.Text(), nullable=True),
    sa.Column('siesa_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['segundo_operario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sesion_origen_id'], ['sesiones_conteo.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesiones_conteo')
    # ### end Alembic commands ###
